<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
use Kumwe\Automation\{CronExpression,JobEnvelope,JobStatus,JobLease,RetryPolicy,FailureClassification,PermanentFailure,TransientFailure,JitterSource,QueueRuntimePolicy,QueueContributionDefinition,JobContributionDefinition,ScheduleContributionDefinition,JobDeclaration,JobHandlerRegistry,JobHandler};
use Kumwe\Context\Value\ExecutionContext;
use Psr\Clock\ClockInterface;
$encoder = new ObservedEncoder();
$now = new DateTimeImmutable('2026-08-04T12:00:00Z');
$job = fn(int $attempts = 2, array $payload = ['id'=>7]) => JobEnvelope::pending($encoder,'00000000-0000-7000-8000-000000000001','default','search.reindex',$payload,$now,$now,maximumAttempts:$attempts);
$pending=$job(); $claimed=$pending->claim('worker-1',$now,30);
check($pending->status()===JobStatus::PENDING && $claimed->attempts()===1,'Claim is immutable and spends exactly one attempt');
check($claimed->status()===JobStatus::RESERVED && $claimed->lease()?->owner()==='worker-1','Claim creates owned lease');
rejects(fn()=> $claimed->claim('worker-2',$now,30),DomainException::class);
rejects(fn()=> $claimed->complete('worker-2',$now),DomainException::class);
rejects(fn()=> $claimed->complete('worker-1',$now->modify('+30 seconds')),DomainException::class);
check($claimed->complete('worker-1',$now->modify('+29 seconds'))->status()===JobStatus::COMPLETED,'Owner completes before exact expiry');
$renewed=$claimed->renewLease('worker-1',$now->modify('+20 seconds'),60);
check($renewed->lease()?->acquiredAt()===$now && $renewed->lease()?->expiresAt()==$now->modify('+80 seconds'),'Renewal retains acquisition and extends expiry');
$retry=$claimed->releaseForRetry('worker-1',$now->modify('+10 seconds'),$now->modify('+60 seconds'));
check(!$retry->isClaimableAt($now->modify('+59 seconds')) && $retry->isClaimableAt($now->modify('+60 seconds')),'Retry availability boundary');
rejects(fn()=> $claimed->releaseForRetry('worker-1',$now->modify('+10 seconds'),$now),InvalidArgumentException::class);
check($job(1)->claim('worker-1',$now,30)->releaseExpiredLease($now->modify('+30 seconds'))->status()===JobStatus::DEAD,'Final expired attempt is dead');
check($claimed->releaseExpiredLease($now->modify('+30 seconds'))->status()===JobStatus::PENDING,'Nonfinal expired attempt is pending');
rejects(fn()=> $claimed->releaseExpiredLease($now->modify('+29 seconds')),DomainException::class);
rejects(fn()=> new JobLease('worker-1',$now,$now));
$encoder->refuse=true; rejects(fn()=> $job()); $encoder->refuse=false;
check($job(payload:['rate'=>1.5])->payload()===['rate'=>1.5],'Generic job encoder may accept floats; declaration rules are separate');
$clock=new class($now) implements ClockInterface {public function __construct(private DateTimeImmutable $time){} public function now():DateTimeImmutable{return $this->time;}};
$jitter=new class implements JitterSource {public array $ranges=[];public int $extra=0; public function between(int $minimum,int $maximum):int{$this->ranges[]=[$minimum,$maximum];return $maximum+$this->extra;}};
$policy=new RetryPolicy($clock,$jitter,10,60);
$decision=$policy->decide(new RuntimeException('temporary'),2,5);
check($decision->delaySeconds===20 && $decision->retryAt==$now->modify('+20 seconds'),'Clock and full jitter are injected');
check($policy->decide(new RuntimeException(),4,5)->delaySeconds===60,'Backoff saturates at maximum');
check(!$policy->decide(new PermanentFailure(),1,5)->shouldRetry,'Permanent failures do not retry');
check(!$policy->decide(new RuntimeException(),5,5)->shouldRetry,'Attempt budget is final');
$transient=new class extends LogicException implements TransientFailure {};
check($policy->classify($transient)===FailureClassification::TRANSIENT,'Explicit transient marker precedes logic fallback');
$jitter->extra=1; rejects(fn()=> $policy->decide(new RuntimeException(),1,5),DomainException::class);
rejects(fn()=> $policy->decide(new RuntimeException(),0,5));
$cron=new CronExpression('*/15 * * * *');
check($cron->next($now->modify('+1 minute 30 seconds'),'UTC')->format(DATE_ATOM)==='2026-08-04T12:15:00+00:00','Cron rounds to next stepped minute');
check((new CronExpression('0 8 * * 1-5'))->next(new DateTimeImmutable('2026-08-04T07:00:00Z'),'Africa/Windhoek')->format(DATE_ATOM)==='2026-08-05T06:00:00+00:00','Cron applies explicit timezone');
check((new CronExpression('0 0 1 * 1'))->next(new DateTimeImmutable('2026-08-02T00:00:00Z'),'UTC')->format('Y-m-d')==='2026-08-03','Restricted day fields use OR semantics');
foreach(['60 * * * *','*/0 * * * *','0 0 32 * *','0 0 * * 8','* * * *'] as $bad) rejects(fn()=> new CronExpression($bad));
$q=new QueueContributionDefinition('acme.queue',30,5,10,90);
check(QueueContributionDefinition::fromArray($q->toArray())->toArray()===$q->toArray(),'Queue declaration roundtrip');
rejects(fn()=> QueueContributionDefinition::fromArray($q->toArray()+['extra'=>true]));
check((new QueueRuntimePolicy('acme.queue',5,1,1,1,0))->toArray()['runtime_generation']===0,'Minimum queue policy bounds');
rejects(fn()=> new QueueRuntimePolicy('acme.queue',4,1,1,1,0));
$definition=new JobContributionDefinition($encoder,'acme.reindex',1,'1.0.0',['type'=>'object']);
check(JobContributionDefinition::fromArray($encoder,$definition->toArray())->toArray()===$definition->toArray(),'Job declaration roundtrip');
$before=$encoder->calls;
foreach([['x'=>1.5],['x'=>new stdClass()],['x'=>array_fill(0,513,1)]] as $bad) rejects(fn()=> new JobContributionDefinition($encoder,'acme.reindex',1,'1.0.0',$bad));
check($encoder->calls===$before,'Declaration policy refuses float/object/oversized collection before injected encoder');
$deep=1;for($i=0;$i<34;$i++)$deep=['x'=>$deep];
rejects(fn()=>new JobContributionDefinition($encoder,'acme.reindex',1,'1.0.0',$deep));
$encoder->bytes=32769; rejects(fn()=>new JobContributionDefinition($encoder,'acme.reindex',1,'1.0.0',['type'=>'object']));$encoder->bytes=null;
$handler=new class implements JobHandler {public function type():string{return 'acme.reindex';}public function handle(array $payload,ExecutionContext $context):void{}};
$registry=new JobHandlerRegistry([$handler]);check($registry->find('acme.reindex')===$handler && $registry->find('missing')===null,'Handler registry resolves exact type');
rejects(fn()=>new JobHandlerRegistry([$handler,$handler]));
fwrite(STDOUT,"automation: $assertions assertions passed\n");
